### ISSUE TITLE
Pylint alerts corrections as part of an intervention experiment

### ISSUE THREAD

**Issue by evidencebp** [TheReverend403/cappuccino#22] opened 2024-12-29 13:38 UTC
Pylint alerts are correlated with tendency to bugs and harder maintenance.
I'd like to conduct a software engineering experiment regarding the benefit of [Pylint](https://pypi.org/project/pylint/) alerts removal.
The experiment is described [here](https://github.com/evidencebp/pylint-intervention/).

In the experiments, Pylint is used with some specific alerts, files are selected for intervention and control.
After the interventions are done, one can wait and examine the results.

Your repository is expected to benefit from the interventions.
I'm asking for your approval for conducting an intervention in your repository.

See examples of interventions in [stanford-oval/storm](https://github.com/stanford-oval/storm/pull/181), [gabfl/vault](https://github.com/gabfl/vault/pull/82), and [coreruleset/coreruleset](https://github.com/coreruleset/coreruleset/pull/3837).

You can see the [planed interventions](https://github.com/evidencebp/pylint-intervention/tree/main/interventions/candidates/TheReverend403_ricedb_interventions_October_04_2024.csv)
The plan is to do 6 interventions in 5 files
The interventions will be of the following types:
line-too-long: 2
too-many-return-statements: 3
too-many-statements: 1

@TheReverend403,  May I do the interventions?

**Comment by evidencebp** [comment] 2024-12-29 13:41
@TheReverend403 , see [PR](https://github.com/TheReverend403/cappuccino/pull/23)

**Comment by evidencebp** [comment] 2024-12-29 14:18
I noticed that the CI/CD [fails](https://github.com/TheReverend403/cappuccino/pull/23/files#annotation_30267413729).
The alert is:
cappuccino/urlinfo.py:246:17: F841 Local variable `hostname` is assigned to but never used

Note that the PR refactors code and the assignment was in the prior version too.

**Comment by lwatsondev** [comment] 2024-12-30 12:05
Hi,

First of all, I'm glad you've taken interest in the project.

I'm a little confused though. It seems you want to check pylint's worth against this project, but we already use [ruff](https://github.com/astral-sh/ruff) for linting and formatting which includes implementations of some [pylint rules](https://docs.astral.sh/ruff/rules/#pylint-pl) so pylint standalone isn't really relevant here.

> Note that the PR refactors code and the assignment was in the prior version too.

This is true for pylint but we use ruff, which is why the CI failed for this PR. Two conflicting linters.

If you can reproduce your experiment with ruff, I'd be happy to consider a PR from that because I do like how you've split a lot of urlinfo.py into smaller functions. ☺️

**Comment by evidencebp** [comment] 2024-12-30 12:29
Ruff and Pylint (and other static analyzers) can add different benefits.
The Pylint alerts existed though the use of Ruff.

The experiment is not about Pylint overall as a static analyzer but on specific alerts.
For example, you can identify too-many-return-statements by simply counting and having too many exit points can be problematic.
I cannot know for sure that your project will benefit from reducing the number of returns since this is the question that the experimt tries to answer.

So, if you think that the changes are good (and thank you for the positive feedbak on urlinfo.py), I'll be happy if you will merge it regardless of the origin of the alerts.
Merging will allow to investigate not only the impact on code metrics (e.g., the number of alerts) but also process metrics (e.g., tendency to bugs, ease of modification).

Regardless of your decision, thank you for the feedback @TheReverend403 !

**Comment by lwatsondev** [comment] 2024-12-30 13:00
Ah, I see. Fair enough, I've merged the PR and fixed the single issue that was preventing the CI completing successfully. Should all be good now.

**Closed as completed** 2024-12-30 13:00 UTC

**Comment by evidencebp** [comment] 2024-12-30 13:39
Thanks!
